language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - pypy
    - pypy3

install:
    - python setup.py install
    - pip install coverage coveralls

script:
    - coverage run --source=src/pyotp ./test.py
#    - coverage report --show-missing

after_success:
    - coveralls

matrix:
  allow_failures:
    - python: pypy3
